version: "1.0"
steps:
  - stepType: Command
    name: Run Application
    timeoutInSeconds: 600
    command: |
      unzip artifacts/app.zip -d /home/ubuntu/deploy_dir
      cd /home/ubuntu/deploy_dir
      chmod +x run.sh
      nohup ./run.sh > deploy.log 2>&1 &
