version: "1.0"
steps:
  - stepType: Command
    name: Run Application
    timeoutInSeconds: 600
    command: |
      unzip artifacts/app.zip -d /tmp/deploy_dir
      cd /tmp/deploy_dir
      chmod +x run.sh
      ./run.sh